namespace Nox.Types;

public enum NoxType
{
    // Complex types
    @Array,
    @Collection,
    @Object,

    // Compound Types - requires multiple fields to pesist
    [CompoundType] Entity,
    [CompoundType] LatLong,
    [CompoundType] Money,
    [CompoundType] StreetAddress,
    [CompoundType] TranslatedText,

    // Simple Types
    Area,
    AutoNumber,
    Boolean,
    Color,
    Colour,
    CountryCode2,
    CountryCode3,
    CountryNumber,
    Culture,
    CurrencyCode,
    CurrencyNumber,
    Date,
    Month,
    Year,
    DateTime,
    DateTimeDuration,
    DateTimeRange,
    DateTimeSchedule,
    Distance,
    Email,
    EncryptedText,
    File,
    Formula,
    Guid,
    HashedText,
    Html,
    Image,
    ImageJpg,
    ImagePng,
    ImageSvg,
    InternetDomain,
    IpAddress,
    Json,
    JwtToken,
    Language,
    Length,
    MacAddress,
    Markdown,
    Nuid,
    Number,
    Password,
    Percentage,
    PhoneNumber,
    Temperature,
    Text,
    Time,
    Uri,
    Url,
    User,
    Volume,
    Weight,
    Yaml,
}